name: run-tests
on:
  push:
    branches:
      - testing
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
      - deployment
jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup node env
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: test
        run: |
          npm ci
          npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
