name: run-tests
on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - dev
      - main
      - deployment
jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: test
        run: |
          npm ci
          npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
