name: run-tests
on:
  pull_request:
    branches:
      - dev
      - main
      - deployment
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: test
        run: |
          npm install
          npm test
