name: run-tests
on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - dev
      - main
      - deployment
jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup node env
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: test
        run: |
          npm ci
          npm run test
      - name: Jest Lcov Reporter
        uses: vebr/jest-lcov-reporter@v0.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
          update-comment: true
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
